"""
Nixtla Schema Transformation Template
Generated by nixtla-schema-mapper skill

Source: [PLACEHOLDER - update with actual source]
Target: Nixtla schema (unique_id, ds, y + exogenous)

Usage:
    from data.transform.to_nixtla_schema import to_nixtla_schema
    df = to_nixtla_schema("data/sales.csv")
"""

import pandas as pd
from pathlib import Path


def to_nixtla_schema(source_path: str = "data/sales.csv") -> pd.DataFrame:
    """
    Transform source data to Nixtla-compatible schema.

    Expected Nixtla schema:
        unique_id (str|int): Series identifier
        ds (datetime): Timestamp
        y (float): Target variable
        [exog_vars]: Optional exogenous features

    Args:
        source_path: Path to source CSV/Parquet file

    Returns:
        DataFrame with Nixtla schema
    """
    # Load data
    if source_path.endswith('.csv'):
        df = pd.read_csv(source_path)
    elif source_path.endswith('.parquet'):
        df = pd.read_parquet(source_path)
    else:
        raise ValueError(f"Unsupported file format: {source_path}")

    # Apply schema transformation
    df_nixtla = df.copy()

    # 1. Map unique_id
    # PLACEHOLDER: Update with actual column name
    df_nixtla['unique_id'] = df['store_id'].astype(str)

    # 2. Map ds (timestamp)
    # PLACEHOLDER: Update with actual column name
    df_nixtla['ds'] = pd.to_datetime(df['date'])

    # 3. Map y (target)
    # PLACEHOLDER: Update with actual column name
    df_nixtla['y'] = pd.to_numeric(df['sales'], errors='coerce')

    # 4. Include exogenous variables (optional)
    # PLACEHOLDER: Update with actual exogenous variable names
    exog_vars = ['price', 'promotion', 'day_of_week', 'holiday']

    # Select final columns
    final_cols = ['unique_id', 'ds', 'y'] + exog_vars
    df_nixtla = df_nixtla[final_cols]

    # Data quality checks
    # Drop rows with missing target
    df_nixtla = df_nixtla.dropna(subset=['y'])

    # Ensure ds is sorted within each series
    df_nixtla = df_nixtla.sort_values(['unique_id', 'ds']).reset_index(drop=True)

    # Validate frequency (optional)
    # Expected: Daily (D), inferred from median time delta
    time_deltas = df_nixtla.groupby('unique_id')['ds'].diff().dt.days.median()
    inferred_freq = 'D' if time_deltas == 1 else f"{int(time_deltas)}D"
    print(f"ℹ️  Inferred frequency: {inferred_freq}")

    return df_nixtla


# Example usage
if __name__ == "__main__":
    # Transform data
    df_nixtla = to_nixtla_schema("data/sales.csv")

    # Inspect result
    print(f"✓ Transformed {len(df_nixtla)} rows")
    print(f"✓ Series count: {df_nixtla['unique_id'].nunique()}")
    print(f"✓ Date range: {df_nixtla['ds'].min()} to {df_nixtla['ds'].max()}")

    print("\nSample:")
    print(df_nixtla.head())

    # Save transformed data (optional)
    output_path = "data/sales_nixtla_schema.parquet"
    df_nixtla.to_parquet(output_path, index=False)
    print(f"\n💾 Saved: {output_path}")
