#!/usr/bin/env python3
"""
TimeGPT Forecasting Pipeline Template
Generated by: Nixtla Claude Code Plugin
Description: Production-ready TimeGPT forecasting pipeline with data validation,
             error handling, visualization, and deployment configurations.
"""

import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import matplotlib.pyplot as plt
import pandas as pd

from nixtla import NixtlaClient

# Setup logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


class TimeGPTForecaster:
    """Production-ready TimeGPT forecasting pipeline."""

    def __init__(self, api_key: Optional[str] = None):
        """Initialize TimeGPT client."""
        self.api_key = api_key or os.getenv("TIMEGPT_API_KEY")
        if not self.api_key:
            raise ValueError(
                "TimeGPT API key required. "
                "Set TIMEGPT_API_KEY environment variable or pass api_key parameter."
            )

        self.client = NixtlaClient(api_key=self.api_key)
        logger.info("TimeGPT client initialized successfully")

    def load_data(self, filepath: str) -> pd.DataFrame:
        """Load and validate time series data."""
        logger.info(f"Loading data from {filepath}")

        # Load data
        df = pd.read_csv(filepath)

        # Validate required columns
        required_cols = ["ds", "y"]  # TimeGPT standard format
        missing_cols = [col for col in required_cols if col not in df.columns]
        if missing_cols:
            raise ValueError(f"Missing required columns: {missing_cols}")

        # Convert date column to datetime
        df["ds"] = pd.to_datetime(df["ds"])

        # Sort by date
        df = df.sort_values("ds")

        # Check for gaps and duplicates
        date_range = pd.date_range(
            start=df["ds"].min(),
            end=df["ds"].max(),
            freq="D",  # Adjust based on your data frequency
        )
        missing_dates = set(date_range) - set(df["ds"])
        if missing_dates:
            logger.warning(f"Found {len(missing_dates)} missing dates in series")

        duplicates = df["ds"].duplicated().sum()
        if duplicates > 0:
            logger.warning(f"Found {duplicates} duplicate dates, keeping first occurrence")
            df = df.drop_duplicates(subset=["ds"], keep="first")

        logger.info(f"Loaded {len(df)} records from {df['ds'].min()} to {df['ds'].max()}")
        return df

    def forecast(
        self,
        df: pd.DataFrame,
        horizon: int,
        freq: str = "D",
        level: Optional[List[int]] = None,
        **kwargs,
    ) -> pd.DataFrame:
        """Generate forecasts using TimeGPT."""
        logger.info(f"Generating {horizon}-period forecast")

        try:
            forecast_df = self.client.forecast(
                df=df,
                h=horizon,
                freq=freq,
                level=level or [80, 95],  # Confidence intervals
                **kwargs,
            )

            logger.info(f"Forecast generated successfully: {len(forecast_df)} periods")
            return forecast_df

        except Exception as e:
            logger.error(f"Forecast failed: {e}")
            raise

    def plot_forecast(
        self,
        historical_df: pd.DataFrame,
        forecast_df: pd.DataFrame,
        save_path: Optional[str] = None,
    ):
        """Visualize historical data and forecast."""
        fig, ax = plt.subplots(figsize=(12, 6))

        # Plot historical data
        ax.plot(
            historical_df["ds"],
            historical_df["y"],
            label="Historical",
            color="black",
            linewidth=1.5,
        )

        # Plot forecast
        ax.plot(
            forecast_df["ds"], forecast_df["TimeGPT"], label="Forecast", color="blue", linewidth=2
        )

        # Plot confidence intervals if available
        if "TimeGPT-lo-95" in forecast_df.columns:
            ax.fill_between(
                forecast_df["ds"],
                forecast_df["TimeGPT-lo-95"],
                forecast_df["TimeGPT-hi-95"],
                alpha=0.2,
                color="blue",
                label="95% CI",
            )

        ax.set_xlabel("Date")
        ax.set_ylabel("Value")
        ax.set_title("TimeGPT Forecast")
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches="tight")
            logger.info(f"Plot saved to {save_path}")

        plt.show()

    def run_pipeline(
        self,
        data_path: str,
        horizon: int,
        freq: str = "D",
        plot: bool = True,
        output_path: Optional[str] = None,
    ) -> pd.DataFrame:
        """Execute complete forecasting pipeline."""
        logger.info("=" * 50)
        logger.info("Starting TimeGPT Forecasting Pipeline")
        logger.info("=" * 50)

        # Load data
        df = self.load_data(data_path)

        # Generate forecast
        forecast_df = self.forecast(df, horizon=horizon, freq=freq)

        # Save results
        if output_path:
            forecast_df.to_csv(output_path, index=False)
            logger.info(f"Forecast saved to {output_path}")

        # Plot
        if plot:
            plot_path = output_path.replace(".csv", ".png") if output_path else None
            self.plot_forecast(df, forecast_df, save_path=plot_path)

        logger.info("=" * 50)
        logger.info("Pipeline completed successfully")
        logger.info("=" * 50)

        return forecast_df

    def forecast_multiple_series(
        self, df: pd.DataFrame, horizon: int, freq: str = "D"
    ) -> pd.DataFrame:
        """Forecast multiple time series identified by 'unique_id' column."""

        # TimeGPT expects 'unique_id', 'ds', 'y' columns
        required_cols = ["unique_id", "ds", "y"]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            raise ValueError(f"Missing required columns for multi-series: {missing}")

        # Forecast all series
        forecast_df = self.client.forecast(df=df, h=horizon, freq=freq, level=[80, 95])

        return forecast_df

    def forecast_with_regressors(
        self, df: pd.DataFrame, horizon: int, X_future: pd.DataFrame, freq: str = "D"
    ) -> pd.DataFrame:
        """Forecast with external regressors."""

        # Historical data with regressors
        forecast_df = self.client.forecast(
            df=df, X_df=X_future, h=horizon, freq=freq  # Future values of regressors
        )

        return forecast_df

    def cross_validate(self, df: pd.DataFrame, horizon: int, n_windows: int = 5) -> pd.DataFrame:
        """Perform time-series cross-validation."""

        cv_results = self.client.cross_validation(
            df=df, h=horizon, n_windows=n_windows, step_size=1
        )

        # Calculate metrics
        from nixtla.utils import accuracy_metrics

        metrics = accuracy_metrics(cv_results)

        logger.info(f"Cross-validation metrics:\n{metrics}")
        return metrics


def main():
    """Main execution function."""
    # Configuration
    DATA_PATH = "data/timeseries.csv"  # TODO: Update with your data path
    HORIZON = 30  # TODO: Update forecast horizon
    FREQ = "D"  # TODO: Update frequency (D=daily, W=weekly, M=monthly)
    OUTPUT_PATH = "output/forecast.csv"  # TODO: Update output path

    # Initialize forecaster
    forecaster = TimeGPTForecaster()

    # Run pipeline
    forecast = forecaster.run_pipeline(
        data_path=DATA_PATH, horizon=HORIZON, freq=FREQ, plot=True, output_path=OUTPUT_PATH
    )

    # Display summary statistics
    print("\n" + "=" * 50)
    print("Forecast Summary")
    print("=" * 50)
    print(forecast.describe())
    print("\nFirst 5 forecasts:")
    print(forecast.head())
    print("\nLast 5 forecasts:")
    print(forecast.tail())


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logger.error(f"Pipeline failed: {e}", exc_info=True)
        sys.exit(1)
