"""
Pytest template generated by nixtla-test-generator.

Replace placeholders and add real assertions.
"""

from __future__ import annotations

import pytest


@pytest.fixture
def sample_input() -> dict:
    return {"example": True}


@pytest.fixture
def mock_client():
    class MockClient:
        def call(self, **_kwargs):
            return {"status": "success"}

    return MockClient()


@pytest.mark.unit
def test_happy_path(sample_input):
    assert sample_input["example"] is True


@pytest.mark.integration
def test_tool_execution(mock_client):
    result = mock_client.call(action="run")
    assert result["status"] == "success"
