{{
  config(
    materialized='table',
    tags=['nixtla', 'forecasting']
  )
}}

/*
Nixtla Schema Transformation (dbt Model)
Generated by nixtla-schema-mapper skill

Source: {{ ref('fct_sales') }} or raw.public.sales
Target: Nixtla schema (unique_id, ds, y)

Usage:
    dbt run --select nixtla_schema
    dbt test --select nixtla_schema
*/

WITH source_data AS (
  SELECT *
  FROM {{ ref('fct_sales') }}  -- Or: raw.public.sales for direct table
  -- PLACEHOLDER: Update with actual source reference
),

nixtla_schema AS (
  SELECT
    -- 1. unique_id: Series identifier
    -- PLACEHOLDER: Update with actual column name
    CAST(store_id AS VARCHAR) AS unique_id,

    -- 2. ds: Timestamp
    -- PLACEHOLDER: Update with actual column name
    CAST(date AS TIMESTAMP) AS ds,

    -- 3. y: Target variable
    -- PLACEHOLDER: Update with actual column name
    CAST(sales AS DOUBLE PRECISION) AS y,

    -- 4. Exogenous variables (optional)
    -- PLACEHOLDER: Update with actual exogenous variable names
    price,
    promotion,
    day_of_week,
    CAST(holiday AS INTEGER) AS holiday

  FROM source_data

  -- Data quality: exclude nulls in target
  WHERE sales IS NOT NULL
)

SELECT *
FROM nixtla_schema
ORDER BY unique_id, ds  -- Ensure chronological order within series
