#!/usr/bin/env python3
"""Report generator for ROI analysis."""

import json
from pathlib import Path
from typing import Any, Optional


def generate_markdown_report(roi_data: dict[str, Any], output_path: Optional[Path] = None) -> str:
    """Generate markdown ROI report."""
    current = roi_data.get("current_costs", {})
    timegpt = roi_data.get("timegpt_costs", {})
    savings = roi_data.get("savings", {})

    report = f"""# TimeGPT ROI Analysis

## Executive Summary

**Recommendation: MIGRATE TO TIMEGPT**

| Metric | Value |
|--------|-------|
| Annual Savings | ${savings.get('annual', 0):,.2f} |
| 3-Year Savings | ${savings.get('3year', 0):,.2f} |
| ROI | {savings.get('roi_percentage', 0):.1f}% |
| Payback Period | {savings.get('payback_months', 0):.1f} months |

---

## Current State Costs (Annual)

| Category | Cost |
|----------|------|
| Tools/Licenses | ${current.get('tool_annual', 0):,.2f} |
| Personnel (FTE) | ${current.get('fte_annual', 0):,.2f} |
| Infrastructure | ${current.get('infrastructure_annual', 0):,.2f} |
| **Total Annual** | **${current.get('total_annual', 0):,.2f}** |
| **3-Year Total** | **${current.get('total_3year', 0):,.2f}** |

---

## TimeGPT Costs (Annual)

| Category | Cost |
|----------|------|
| API Usage | ${timegpt.get('api_annual', 0):,.2f} |
| Personnel (Reduced) | ${timegpt.get('fte_annual', 0):,.2f} |
| **Total Annual** | **${timegpt.get('total_annual', 0):,.2f}** |
| **3-Year Total** | **${timegpt.get('total_3year', 0):,.2f}** |

---

## Key Benefits

1. **70% Reduction in Data Scientist Time**: Focus on business problems, not model tuning
2. **Zero Infrastructure**: No GPU/compute management needed
3. **Instant Forecasts**: Sub-second API response vs hours of training
4. **State-of-the-Art Accuracy**: Foundation model trained on 100B+ time points

---

*Generated by Nixtla ROI Calculator*
"""

    if output_path:
        output_path.write_text(report)

    return report


def generate_salesforce_export(roi_data: dict[str, Any], opportunity_name: str) -> dict:
    """Generate Salesforce opportunity export format."""
    savings = roi_data.get("savings", {})

    return {
        "Name": opportunity_name,
        "Amount": savings.get("3year", 0),
        "Description": f"TimeGPT migration - {savings.get('roi_percentage', 0):.1f}% ROI",
        "StageName": "Qualification",
        "Type": "New Business",
        "LeadSource": "ROI Calculator",
        "Custom_Fields": {
            "Annual_Savings__c": savings.get("annual", 0),
            "ROI_Percentage__c": savings.get("roi_percentage", 0),
            "Payback_Months__c": savings.get("payback_months", 0),
            "Current_Annual_Cost__c": roi_data.get("current_costs", {}).get("total_annual", 0),
            "Proposed_Annual_Cost__c": roi_data.get("timegpt_costs", {}).get("total_annual", 0),
        },
    }
