#!/usr/bin/env python3
"""MCP Server for Nixtla Snowflake Adapter.

Generates SQL for Nixtla Snowflake Native App and validates installations.
"""

import json
import os
from typing import Any, Optional

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

app = Server("nixtla-snowflake-adapter")


def generate_forecast_sql(
    table: str,
    timestamp_col: str = "ds",
    value_col: str = "y",
    group_by_col: Optional[str] = None,
    horizon: int = 30,
    freq: str = "D",
    levels: list[int] = [80, 90, 95],
) -> str:
    """Generate CALL NIXTLA_FORECAST SQL."""
    sql = f"""-- Generated by nixtla-snowflake-adapter
-- Execute in Snowflake to generate forecasts

CALL NIXTLA.FORECAST(
    INPUT_TABLE => '{table}',
    TIMESTAMP_COL => '{timestamp_col}',
    VALUE_COL => '{value_col}',"""

    if group_by_col:
        sql += f"\n    GROUP_BY_COL => '{group_by_col}',"

    sql += f"""
    HORIZON => {horizon},
    FREQUENCY => '{freq}',
    LEVEL => ARRAY_CONSTRUCT({', '.join(map(str, levels))})
);

-- View results
SELECT *
FROM NIXTLA.FORECAST_RESULTS
WHERE FORECAST_DATE > CURRENT_DATE
ORDER BY {"'" + group_by_col + "', " if group_by_col else ""}FORECAST_DATE;
"""
    return sql


def generate_setup_validation_sql() -> str:
    """Generate SQL to validate Nixtla Native App setup."""
    return """-- Nixtla Snowflake Native App Setup Validation
-- Run each section to validate your installation

-- 1. Check Nixtla app is installed
SHOW APPLICATIONS LIKE 'NIXTLA%';

-- 2. Verify permissions
SHOW GRANTS ON APPLICATION NIXTLA;

-- 3. Check available functions
DESCRIBE FUNCTION NIXTLA.FORECAST;
DESCRIBE FUNCTION NIXTLA.DETECT_ANOMALIES;
DESCRIBE FUNCTION NIXTLA.CROSS_VALIDATE;

-- 4. Test with sample data
CREATE OR REPLACE TEMPORARY TABLE test_data AS
SELECT
    'series_1' as unique_id,
    DATEADD(day, seq4(), '2024-01-01')::DATE as ds,
    100 + (seq4() * 0.5) + UNIFORM(-5, 5, RANDOM()) as y
FROM TABLE(GENERATOR(ROWCOUNT => 100));

-- 5. Run test forecast
CALL NIXTLA.FORECAST(
    INPUT_TABLE => 'test_data',
    TIMESTAMP_COL => 'ds',
    VALUE_COL => 'y',
    GROUP_BY_COL => 'unique_id',
    HORIZON => 7,
    FREQUENCY => 'D'
);

-- 6. View test results
SELECT * FROM NIXTLA.FORECAST_RESULTS;

-- Cleanup
DROP TABLE IF EXISTS test_data;
"""


@app.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="generate_forecast_sql",
            description="Generate CALL NIXTLA_FORECAST SQL",
            inputSchema={
                "type": "object",
                "properties": {
                    "table": {"type": "string", "description": "Source table name"},
                    "timestamp_col": {"type": "string", "default": "ds"},
                    "value_col": {"type": "string", "default": "y"},
                    "group_by_col": {"type": "string"},
                    "horizon": {"type": "integer", "default": 30},
                    "freq": {"type": "string", "default": "D"},
                    "levels": {
                        "type": "array",
                        "items": {"type": "integer"},
                        "default": [80, 90, 95],
                    },
                },
                "required": ["table"],
            },
        ),
        Tool(
            name="validate_setup",
            description="Generate SQL to validate Nixtla Native App setup",
            inputSchema={"type": "object", "properties": {}},
        ),
        Tool(
            name="generate_anomaly_sql",
            description="Generate CALL NIXTLA_DETECT_ANOMALIES SQL",
            inputSchema={
                "type": "object",
                "properties": {
                    "table": {"type": "string"},
                    "timestamp_col": {"type": "string", "default": "ds"},
                    "value_col": {"type": "string", "default": "y"},
                    "level": {"type": "integer", "default": 95},
                },
                "required": ["table"],
            },
        ),
        Tool(
            name="export_looker_view",
            description="Generate Looker view for forecast results",
            inputSchema={
                "type": "object",
                "properties": {"view_name": {"type": "string", "default": "nixtla_forecasts"}},
            },
        ),
    ]


@app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    if name == "generate_forecast_sql":
        sql = generate_forecast_sql(
            table=arguments["table"],
            timestamp_col=arguments.get("timestamp_col", "ds"),
            value_col=arguments.get("value_col", "y"),
            group_by_col=arguments.get("group_by_col"),
            horizon=arguments.get("horizon", 30),
            freq=arguments.get("freq", "D"),
            levels=arguments.get("levels", [80, 90, 95]),
        )
        return [TextContent(type="text", text=sql)]

    elif name == "validate_setup":
        return [TextContent(type="text", text=generate_setup_validation_sql())]

    elif name == "generate_anomaly_sql":
        table = arguments["table"]
        sql = f"""CALL NIXTLA.DETECT_ANOMALIES(
    INPUT_TABLE => '{table}',
    TIMESTAMP_COL => '{arguments.get("timestamp_col", "ds")}',
    VALUE_COL => '{arguments.get("value_col", "y")}',
    LEVEL => {arguments.get("level", 95)}
);

SELECT * FROM NIXTLA.ANOMALY_RESULTS WHERE is_anomaly = TRUE;
"""
        return [TextContent(type="text", text=sql)]

    elif name == "export_looker_view":
        view_name = arguments.get("view_name", "nixtla_forecasts")
        lkml = f"""view: {view_name} {{
  sql_table_name: NIXTLA.FORECAST_RESULTS ;;

  dimension: unique_id {{
    type: string
    sql: ${{TABLE}}.unique_id ;;
  }}

  dimension_group: forecast {{
    type: time
    timeframes: [date, week, month]
    sql: ${{TABLE}}.forecast_date ;;
  }}

  measure: forecast_value {{
    type: average
    sql: ${{TABLE}}.forecast_value ;;
  }}

  measure: forecast_lower {{
    type: average
    sql: ${{TABLE}}.forecast_lo_80 ;;
  }}

  measure: forecast_upper {{
    type: average
    sql: ${{TABLE}}.forecast_hi_80 ;;
  }}
}}
"""
        return [TextContent(type="text", text=lkml)]

    return [TextContent(type="text", text=f"Unknown tool: {name}")]


async def main():
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
